### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by madmurdock** [Codercamp/codercamp.github.io#11]
So, I kinda wanted to start naming things like torrents:

i.e. CoderCampHamilton_S16E02_bpoetz-incognito.ppt.

Neat? Lame?

**Comment by Incognito** [comment]
i'm indifferent on this one. You lose knowledge of the date it happened, but I don't know if anyone cares about that in practice.

**Comment by codercampHamOnt** [comment]
No more than "CoderCamp 16 01"

**Comment by rprouse** [comment]
The date would still be preserved. It is required for posts in Jekyll. You could use that naming format for coder camps going forward. I would prefer to see `CoderCamp S05E01` over `CoderCamp 16 01` :+1:

**Comment by bpoetz** [comment]
closing this issue, I'll follow AJ's new convention
