### ISSUE TITLE
Can I truncate the history?

### ISSUE THREAD

**Issue by Incognito** [Codercamp/codercamp.github.io#12]
We have commit history going all the way back in time to the origin of the project. I'd like to truncate it so we can keep the contributors page just to people who contribute to CCH.

**Comment by rprouse** [comment]
That is my fault. I originally forked the repo from a Jekyll blogging platform. I ended up not liking it and overwrote everything, but the history remains.

Truncating the old history is dangerous, but I think it can be done. It will require a force push and we should make a backup just in case.  http://jedidjah.ch/code/2014/8/28/purge_old_git_history/

**Comment by rprouse** [comment]
We would want to delete all history before a13da500c24624032621bfc9be54346bb6850582

**Comment by Incognito** [comment]
Fyi, there's new methods to do the job, grafting is no longer needed.

On Fri, Jan 15, 2016 at 12:01 PM, Rob Prouse <notifications@github.com>
wrote:

> We would want to delete all history before a13da50
> <https://github.com/Codercamp/codercamp.github.io/commit/a13da500c24624032621bfc9be54346bb6850582>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codercamp/codercamp.github.io/issues/12#issuecomment-172016332>
> .
>



-- 
-Brian G.

**Comment by bpoetz** [comment]
Hey Incognito, how can we do this?

**Comment by Incognito** [comment]
Yup,

Off-hand it would be something like interactive rebase the history and squash all previous stuff (be sure to truncate the squashed commit message as github lags on big messages). `git rebase -i 4c18ec` (replace everything before a13da50 with a squash command).

Or you could create a branch with the --orphan flag so it has no common ancestor with master, commit jekyll as one big blob, then cherry-pick the range of work done here (but you'll lose merge commits... I think there's a flag to preserve it but I forget how I've done that in the past...)

There's also a command `git replace` http://git-scm.com/2010/03/17/replace.html

It might be nice to practice what you like best, because eventually Jekyll will have new features or bug fixes we can just rebase our code ontop of without changing our history or inserting "changing jekyll" commits.

**Comment by rprouse** [comment]
The base of the repo is not Jekyll, but a Jekyll based template that I
ended up overwriting, so we will never pull in latest from Jekyll. Jekyll
isn't actually part of this repo, it is a node package that transforms what
is in the repo.

On 26 January 2016 at 09:30, Brian Graham <notifications@github.com> wrote:

> Yup,
>
> Off-hand it would be something like interactive rebase the history and
> squash all previous stuff (be sure to truncate the squashed commit message
> as github lags on big messages). git rebase -i 4c18ec (replace everything
> before a13da50
> <https://github.com/Codercamp/codercamp.github.io/commit/a13da500c24624032621bfc9be54346bb6850582>
> with a squash command).
>
> Or you could create a branch with the --orphan flag so it has no common
> ancestor with master, commit jekyll as one big blob, then cherry-pick the
> range of work done here (but you'll lose merge commits... I think there's a
> flag to preserve it but I forget how I've done that in the past...)
>
> There's also a command git replace
> http://git-scm.com/2010/03/17/replace.html
>
> It might be nice to practice what you like best, because eventually Jekyll
> will have new features or bug fixes we can just rebase our code ontop of
> without changing our history or inserting "changing jekyll" commits.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codercamp/codercamp.github.io/issues/12#issuecomment-175044818>
> .
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by bpoetz** [comment]
Thanks for the rundown, @incognito, and the clarification, @rprouse.

**Comment by rprouse** [comment]
Okay, that was a bit scary. The history is now truncated back to when I created the site. https://github.com/Codercamp/codercamp.github.io/graphs/contributors
