### ISSUE TITLE
bundle install fails

### ISSUE THREAD

**Issue by madmurdock** [Codercamp/codercamp.github.io#14]
Not sure where i'm going wrong, but bundle install fails when trying to get my local running.

**Comment by bpoetz** [comment]
do u have an error message?

**Comment by madmurdock** [comment]
c:/tools/ruby21/bin/ruby.exe extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
generating stemmer-x64-mingw32.def
compiling porter.c
porter.c: In function 'step1ab':
porter.c:233:4: warning: passing argument 2 of 'ends' discards 'const' qualifier from pointer target type [enabled by default]

last line repeats a few hundred times

**Comment by madmurdock** [comment]
c:/tools/ruby21/bin/ruby.exe extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
generating generator-x64-mingw32.def
compiling generator.c
make: x86_64-w64-mingw32-gcc: Command not found
make: *** [generator.o] Error 127

make failed, exit code 2

**Comment by madmurdock** [comment]
possible that devkit didn't install properly?

**Comment by bpoetz** [comment]
My guess, but I don't window.  Want me test yr pr?

**Comment by madmurdock** [comment]
please. I imagine the "E" in the event title will be lowercase.

**Comment by rprouse** [comment]
Looks like a bad devkit install to me. Could also be path issues. Did you try a reboot after installing?

**Comment by madmurdock** [comment]
ya, i dunno what i'm doing. typical "run this linux stuff on windows" problems

**Comment by bpoetz** [comment]
I have merged your PR, it looked good

**Comment by bpoetz** [comment]
closing as wontfix, this is an upstream issue with the user's machine.  Install a good OS.

**Comment by bpoetz** [comment]
I just wanted to leave you a note that says that I had to print from Nageeb's machine today because CUPS isn't working on my machine.  So I'm not actually proclaiming "year of the linux desktop" here, just being a weenie.

**Comment by madmurdock** [comment]
ya fixed. it requires devkit 64bit, and --force to overwrite the previous install

**Comment by madmurdock** [comment]
crapping out on kramdown now. quitting.

**Comment by bpoetz** [comment]
virtual machine?
