### ISSUE TITLE
Need a meetup.com page setup

### ISSUE THREAD

**Issue by madmurdock** [Codercamp/codercamp.github.io#18]
Eventbrite is good, but tons of people always ask me why we're not on meetup.com.  No reason we can't do both... thoughts?

**Comment by rprouse** [comment]
It does seem like more of a meet up than a ticketed event, but I think we should choose one or the other, not both to prevent confusion. Do you think meetup might bring in new people? I have searched meetup for developer events in the past, so it might help. I've never searched eventbrite.

**Comment by madmurdock** [comment]
Meetup has more of a community feel to it, but I think you have to register an account to play (which always irks me).  Going on the SEO talk from a few months, we should be planting flags everywhere.  We only really use eventbrite for:

1) seeing if anyone's coming
2) seeing if alot of people are coming
3) sending spammy emails for the next event

**Comment by bpoetz** [comment]
http://www.meetup.com/pricing/ 10 usd a month.

**Comment by madmurdock** [comment]
pfffffffff nevermind!

**Comment by bpoetz** [comment]
agree on the general idea abt. planting seeds everywhere. facebook group?

**Comment by madmurdock** [comment]
We need a list. and a rake script to update them all automatically...

**Comment by bpoetz** [comment]
Can we use cake or hake or jake or make instead?

**Comment by madmurdock** [comment]
http://listmoz.com/#pnNYVhVmZc46gyfgrwT

**Comment by rprouse** [comment]
IFTTT, is pretty good at setting up rules and piping info to various services. Not sure if it would work for this, but I can check the endpoints. Pretty sure there isn't an eventbrite one ;)
