### ISSUE TITLE
Migrate from eventbrite

### ISSUE THREAD

**Issue by madmurdock** [Codercamp/codercamp.github.io#30]
I'd like to move things away from eventbrite, just because i hate having to publish the events in 2 places (Website and eb). And EB is a pain in the ass.

**Comment by bpoetz** [comment]
yeah.  Wordpress?

**Comment by madmurdock** [comment]
Wagtail? cc @emilyhorsman

**Comment by bpoetz** [comment]
:) probably good with just using this for now,  cutting out eventbrite
completely.  I talked to Mallory at the plucker and she said they couldn't
call anyone in anyways...

**Comment by madmurdock** [comment]
That's funny. I still like getting a reading on how many people are coming, and being aware of new people showing up. Maybe eventbrite has an api...

**Comment by bpoetz** [comment]
Me too,  maybe we could write our own api,  and use at as an opportunity to
pair again?

**Comment by madmurdock** [comment]
https://www.eventbrite.ca/developer/v3/endpoints/events/#ebapi-post-events

**Comment by madmurdock** [comment]
maybe build a publishing tool that will create and publish the .md to the github site, publish an eventbrite event, tweet, fb, whatever.  I just wanna do it once, maybe bot it so it does auto-promo spam ;)

**Comment by bpoetz** [comment]
that was supposed to be 👍

**Comment by rprouse** [comment]
I have purchased a Meetup.com account and setup https://www.meetup.com/CoderCamp-Hamilton/ for future use. I was in a call with other event organizers and they said that switching from Eventbrite to Meetup boosted their attendance dramatically.

The initial event is setup, I just need to update the website to point registration here instead.
