### ISSUE TITLE
Exclude past events from upcoming events

### ISSUE THREAD

**Issue by mirhagk** [Codercamp/codercamp.github.io#44]
As @rprouse mentioned in #43 it'd be nice to only show actual upcoming events in the upcoming events section so it didn't require constant updating.

I'm creating this issue to create some discussion on it. I have 2 potential solutions:

1. If this is built with CI, you could potentially have it build daily and then filter the posts that are in the past. From some quick googling these pages would appear to be useful. (Instead of once a day it might be sufficient to rebuild manually at the end of each event)

+ http://stackoverflow.com/questions/9623719/only-return-jekyll-posts-that-match-specific-year 
+ http://stackoverflow.com/questions/12464656/get-todays-date-in-jekyll-with-liquid-markup

2. You could show X upcoming events (like say 5) and use client side javascript to filter out ones that are in the past. It'll produce a bit of a flash where the events appear and then disappear though.

I'm willing to take a look at this, but which solution do you think is better?

**Comment by rprouse** [comment]
The website is built automatically by GitHub on changes to master and I don't think we can plug into that pipeline. We can go through the GitHub help though to be sure.

If we take the Javascript approach, we could start hidden and fade in the posts one at a time to prevent the flicker. Might cause people without JS running to not see the events though.

**Comment by mirhagk** [comment]
Is the noscript tag still a thing? We could include like 2-3 events in a noscript tag as a fallback.

If it's automatically built with github we could always just make a horrible commit history with automated check-ins 😛
