### ISSUE TITLE
Talk in February?

### ISSUE THREAD

**Issue by mirhagk** [Codercamp/codercamp.github.io#50]
I'm not sure if it's too soon to give a talk again, but I just came up with a really fun topic.

It's on the git blame tool, and using it to figure out why the heck the code is doing that funky thing (and of course find the person to blame... er I mean find out who to ask about the reason for the change 😛).

I think the January date would be too soon, but maybe February? Is there any kind of protocol as to how often people have to listen to me talk?

**Comment by Incognito** [comment]
If you give the talk here's two more tips from things I use which are not `git blame`:

1. `git log <file> -p --follow` to see the intent of historical commits on a file, and who shipped the intent (useful when you're on projects with many developers).

2. `git bisect` for finding the commit that made things go cray cray (check out http://webchick.net/node/99 for a description).

**Comment by mirhagk** [comment]
Thanks for the tips. I will mention bisect for sure.

For the `git log -p --follow <file>`, this gives you a nice view of all the changes the occurred to a file with the commit details and the actual changed lines, right? So you use this to view all the changes on a file, looking for what looks like the change you want?

**Comment by Incognito** [comment]
Exactly, I often find a single line of code doesn't really tell me what the person was thinking, which means I don't know what their intention behind the change was. This helps me broaden context when a single line of code doesn't do it, or the person's left the org.

**Comment by mirhagk** [comment]
Yeah makes sense. I'm going to do part of the talk covering the GUI tool I use (visual studio) which lets you do a very similar thing. I do the equivalent of git blame, and then go to the commit to view the changes, commit details (also which other files changed) to get an idea of why that was happening. 

When I get some slides prepared, would you mind reviewing it so that I got the command line part covered appropriately? I don't tend to use the command line as much, so I want to make sure I'm not missing anything important

**Comment by Incognito** [comment]
Sure, post the link when you have it.
